---
- name: Apply base prometheus exporter role
  ansible.builtin.import_role:
    name: wandansible.prometheus_exporter

- block:
    - name: Create blackbox_exporter configuration directory
      ansible.builtin.file:
        state: directory
        path: "{{ blackbox_exporter_config_file | dirname }}"
        owner: root
        group: root
        mode: u=rwx,g=rx,o=rx

    - name: Add blackbox_exporter configuration
      ansible.builtin.template:
        src: config.yml
        dest: "{{ blackbox_exporter_config_file }}"
        owner: root
        group: root
        mode: u=rw,g=r,o=r
      notify: restart {{ exporter_service }}
  when: exporter_install | bool

- name: Register blackbox_exporter probe targets
  ansible.builtin.include_tasks:
    file: probe.yml
  loop: "{{ blackbox_exporter_probe_targets }}"
  loop_control:
    label: "{{ item.type }}"
