---
- name: Apply base prometheus exporter role
  ansible.builtin.import_role:
    name: wandansible.prometheus_exporter

- block:
    - name: Add CAP_NET_RAW capability to blackbox_exporter binary for ICMP probes (libcap2 < 2.41)
      community.general.capabilities:
        path: "{{ exporter_bin_dir }}/{{ exporter_binary }}"
        capability: cap_net_raw+ep
        state: present
      notify: restart {{ exporter_service }}
      when: >-
        (ansible_distribution == 'Ubuntu' and ansible_distribution_version is version('20.10', '<'))
        or (ansible_distribution == 'Debian' and ansible_distribution_version is version('11', '<'))

    - name: Add CAP_NET_RAW capability to blackbox_exporter binary for ICMP probes (libcap2 2.41+)
      community.general.capabilities:
        path: "{{ exporter_bin_dir }}/{{ exporter_binary }}"
        capability: cap_net_raw=ep
        state: present
      notify: restart {{ exporter_service }}
      when: >-
        (ansible_distribution == 'Ubuntu' and ansible_distribution_version is version('20.10', '>='))
        or (ansible_distribution == 'Debian' and ansible_distribution_version is version('11', '>='))

    - name: Allow all groups to send ICMP packets
      ansible.posix.sysctl:
        key: "net.ipv4.ping_group_range"
        value: "0   2147483647"
        sysctl_file: "/etc/sysctl.d/blackbox_exporter.conf"

    - name: Create blackbox_exporter configuration directory
      ansible.builtin.file:
        state: directory
        path: "{{ blackbox_exporter_config_file | dirname }}"
        owner: root
        group: root
        mode: u=rwx,g=rx,o=rx

    - name: Add blackbox_exporter configuration
      ansible.builtin.template:
        src: config.yml
        dest: "{{ blackbox_exporter_config_file }}"
        owner: root
        group: root
        mode: u=rw,g=r,o=r
      notify: restart {{ exporter_service }}
  when: exporter_install | bool

- name: Register blackbox_exporter probe targets
  ansible.builtin.include_tasks:
    file: probe.yml
  loop: "{{ blackbox_exporter_probe_targets }}"
  loop_control:
    label: "{{ item.type }}"
