---
- name: Create blackbox_exporter service discovery probe directory ({{ _probe_targets.key }})
  ansible.builtin.file:
    path: "{{ blackbox_exporter_file_sd_probe_dir }}/{{ _probe_targets.key }}"
    state: directory
    owner: root
    group: root
    mode: u=rwx,g=rx,o=rx
  delegate_to: "{{ item }}"
  loop: "{{ exporter_scrape_servers }}"

- name: Register blackbox_exporter probe targets ({{ _probe_targets.key }})
  ansible.builtin.template:
    src: targets.yml
    dest: "{{ blackbox_exporter_file_sd_probe_dir }}/{{ _probe_targets.key }}/{{ inventory_hostname }}.yml"
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  delegate_to: "{{ item }}"
  loop: "{{ exporter_scrape_servers }}"
  vars:
    targets: "{{ _probe_targets.value }}"
