---
- name: Create blackbox_exporter service discovery probe directory ({{ item.type }})
  ansible.builtin.file:
    path: "{{ blackbox_exporter_file_sd_probe_dir }}/{{ item.type }}"
    state: directory
    owner: root
    group: root
    mode: u=rwx,g=rx,o=rx
  delegate_to: "{{ _scrape_server }}"
  loop: "{{ exporter_scrape_servers }}"
  loop_control:
    loop_var: _scrape_server

- name: Register blackbox_exporter probe targets ({{ item.type }})
  ansible.builtin.template:
    src: targets.yml
    dest: "{{ blackbox_exporter_file_sd_probe_dir }}/{{ item.type }}/{{ inventory_hostname }}.yml"
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  delegate_to: "{{ _scrape_server }}"
  loop: "{{ exporter_scrape_servers }}"
  loop_control:
    loop_var: _scrape_server
