---
- name: Converge
  hosts: all
  tasks:
    - name: "Include wandansible.prometheus_exporter.blackbox"
      ansible.builtin.include_role:
        name: "wandansible.prometheus_exporter.blackbox"
      vars:
        blackbox_exporter_github_token: "{{ lookup('env', 'GITHUB_TOKEN') }}"
