---
- name: Prepare
  hosts: all
  tasks:
    - name: "Install getcap/setcap"
      ansible.builtin.apt:
        pkg:
          - "libcap2-bin"

    - name: "Install sysctl"
      ansible.builtin.apt:
        pkg:
          - "procps"
